function getRandomNum() {
    return Math.floor(Math.random() * 10000);
};

const usersData = [
    {
        "name": "John Doe",
        "username": "doenut-reviews",
        "following": 5,
        "followers": 6,
        "isFollowing": true,
    },
    {
        "name": "Mary Jane",
        "username": "marysmovies",
        "following": 291,
        "followers": 62,
        "isFollowing": true,
    },
    {
        "name": "Bingo Boffman",
        "username": "bingo_was_his_name",
        "following": 101,
        "followers": 111,
        "isFollowing": true,
    },
    {
        "name": "Jonah Babona",
        "username": "notjonahhill",
        "following": 249,
        "followers": 294,
        "isFollowing": true,
    },
    {
        "name": "Jason Mimoa",
        "username": "aquaman",
        "following": 10,
        "followers": 19348,
        "isFollowing": true,
    },
    {
        "name": "John Stamos",
        "username": "best-uncle",
        "following": 459,
        "followers": 1903,
        "isFollowing": true,
    },
    {
        "name": "Dwayne Johnson",
        "username": "the-rock",
        "following": 5,
        "followers": 390506,
        "isFollowing": true,
    },
    {
        "name": "Zach Braff",
        "username": "braffster",
        "following": 51,
        "followers": 634,
        "isFollowing": true,
    },
    {
        "name": "Roy Williams",
        "username": "beatcoachk",
        "following": 50,
        "followers": 63050,
        "isFollowing": true,
    },
    {
        "name": "Jonah Hill",
        "username": "officalJonah",
        "following": 21,
        "followers": 34908,
        "isFollowing": true,
    },
    {
        "name": "Keanu Reeves",
        "username": "reeving-reviews",
        "following": 530,
        "followers": 6294,
        "isFollowing": true,
    },
    {
        "name": "Stevie Wonder",
        "username": "wonderman",
        "following": 29,
        "followers": 623499,
        "isFollowing": true,
    },
    {
        "name": "Byron Nadine",
        "username": "byron",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Jimmie Nat",
        "username": "jimmie",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Haleigh Yancy",
        "username": "haleigh",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Gladwin Hardy",
        "username": "glad",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Pru Jools",
        "username": "jewels",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Joanie Rafferty",
        "username": "joanie",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Emely Jo",
        "username": "emelz",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Rorie Chloe",
        "username": "rorie",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Ginger Nolene",
        "username": "ginger-snap",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Katharine Mitch",
        "username": "kath",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Marina Denise",
        "username": "mari",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Ilbert Merrill",
        "username": "bert",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Madyson Camron",
        "username": "madz",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Greta Gaye",
        "username": "greta",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Jodie Sophia",
        "username": "jodsof",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Davis Misty",
        "username": "misty",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Dewey Irene",
        "username": "dewey_decimal_system",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Shayla Jenae",
        "username": "jenaenae",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
    {
        "name": "Sandra Issac",
        "username": "sandra_",
        "following": getRandomNum(),
        "followers": getRandomNum(),
        "isFollowing": false,
    },
];

export default usersData